// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/subscriptions": {
            "get": {
                "description": "Retrieve a list of all subscriptions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "List all subscriptions",
                "responses": {
                    "200": {
                        "description": "List of subscriptions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.SubscriptionResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new subscription with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Create a new subscription",
                "parameters": [
                    {
                        "description": "Subscription creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Subscription created successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.SubscriptionResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/stats": {
            "post": {
                "description": "Collect statistics for subscriptions within a date range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Collect subscription statistics",
                "parameters": [
                    {
                        "description": "Statistics collection request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SumSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Statistics collected successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.SumSubscriptionResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "get": {
                "description": "Retrieve a subscription by its unique ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Get a subscription by ID",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subscription found",
                        "schema": {
                            "$ref": "#/definitions/dto.SubscriptionResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing subscription by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Update a subscription",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Subscription update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Subscription updated successfully",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateSubscriptionResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a subscription by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Delete a subscription",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - Subscription deleted successfully"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateSubscriptionRequest": {
            "description": "Request body for creating a new subscription",
            "type": "object",
            "required": [
                "price",
                "service_name",
                "start_date",
                "user_id"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "12-2024"
                },
                "price": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 999
                },
                "service_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "enum": [
                        "Netflix",
                        "Spotify",
                        "Apple Music"
                    ],
                    "example": "Netflix"
                },
                "start_date": {
                    "type": "string",
                    "example": "01-2024"
                },
                "user_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "dto.SubscriptionResponse": {
            "description": "Response containing updated subscription fields",
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "12-2024"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "integer",
                    "example": 999
                },
                "service_name": {
                    "type": "string",
                    "example": "Netflix"
                },
                "start_date": {
                    "type": "string",
                    "example": "01-2024"
                },
                "user_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "dto.SumSubscriptionRequest": {
            "description": "Request body for collecting subscription statistics",
            "type": "object",
            "required": [
                "end_period",
                "start_period"
            ],
            "properties": {
                "end_period": {
                    "type": "string",
                    "example": "12-2024"
                },
                "service_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Netflix"
                },
                "start_period": {
                    "type": "string",
                    "example": "01-2024"
                },
                "user_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "dto.SumSubscriptionResponse": {
            "description": "Response containing subscription details",
            "type": "object",
            "properties": {
                "total_count": {
                    "type": "integer",
                    "example": 10
                },
                "total_sum": {
                    "type": "integer",
                    "example": 15
                }
            }
        },
        "dto.UpdateSubscriptionRequest": {
            "description": "Request body for updating an existing subscription",
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "01-2024"
                },
                "price": {
                    "type": "integer",
                    "example": 999
                },
                "service_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Netflix"
                }
            }
        },
        "dto.UpdateSubscriptionResponse": {
            "description": "Response containing subscription statistics",
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "12-2024"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "price": {
                    "type": "integer",
                    "example": 999
                },
                "service_name": {
                    "type": "string",
                    "example": "Netflix"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/subscriptions",
	Schemes:          []string{},
	Title:            "Subscriptions API",
	Description:      "CRUDL subscription service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
